#!/bin/sh

~/bin/base_launch "sxhkd" &
~/bin/base_launch "picom" &

bspc monitor -d I II III IV V

# gruvbox
#bspc config normal_border_color "#3c3836"
#bspc config focused_border_color "#689d6a"
#bspc config urgent_border_color "#cc241d"
#bspc config presel_border_color "#8ec07c"

# pywal
. "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color "$color2"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config urgent_border_color "$color4"
bspc config presel_border_color "$color9"

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true 
bspc config top_padding 20

bspc rule -a "Discord Updater" state=floating 
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/bin/base_launch "polybar" &
~/bin/base_launch "dunst" &
pywalfox update &
#~/bin/base_launch "oneko -tora -bg white -fg black -speed 25 -position +0-30" &
#~/bin/base_launch "redshift-gtk" &
~/bin/base_launch "xsetroot -cursor_name left_ptr" &
~/.fehbg &
